name: Deploy to Render (Yarn)
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_YARN }}
          api-key: ${{ secrets.RENDER_API_KEY_YARN }}
